### ISSUE TITLE
Define before_scenario() and after_scenario() in environment.py

### ISSUE THREAD

**Issue by chelmertz** [tvestelind/lottery#1]
As stated on https://pythonhosted.org/behave/api.html#environment-file-functions

>The environment.py module may define code to run before and after certain events during your testing: [...]

So, you should pull out `before_scenario()` and `after_scenario()` to features/environment.py

// the one who spent an hour trying to get it working, manuals are for weaklings..

**Comment by tvestelind** [comment]
Thank you for pointing this out. Fixed in branch creation.
